-- Tabela FORNECEDOR_EXT
CREATE TABLE FORNECEDOR_EXT (
    codigo NUMBER PRIMARY KEY,
    nome VARCHAR2(100)
);

-- Tabela ALMOXARIFADO
CREATE TABLE ALMOXARIFADO (
    codigo NUMBER PRIMARY KEY,
    nome VARCHAR2(60),
    rua VARCHAR2(100),
    nr VARCHAR2(10),
    bairro VARCHAR2(50),
    cidade VARCHAR2(30),
    uf VARCHAR2(2),
    situacao VARCHAR2(7),
    CONSTRAINT UK_DESCR_ALM UNIQUE (nome)
);

-- Tabela MERCADORIA
CREATE TABLE MERCADORIA (
    codigo NUMBER PRIMARY KEY,
    descricao VARCHAR2(100),
    unidade_medida VARCHAR2(10)
);

-- Tabela EMPREGADO
CREATE TABLE EMPREGADO (
    matricula NUMBER PRIMARY KEY,
    nome VARCHAR2(100),
    funcao VARCHAR2(200)
);

-- Tabela ENTRADA_MERCADORIA
CREATE TABLE ENTRADA_MERCADORIA (
    data DATE,
    MER_codigo NUMBER,
    ALM_codigo NUMBER,
    quantidade NUMBER(4),
    FOR_codigo NUMBER,
    PRIMARY KEY (MER_codigo, ALM_codigo, data),
    CONSTRAINT FK_ENTMER_MER FOREIGN KEY (MER_codigo) REFERENCES MERCADORIA (codigo),
    CONSTRAINT FK_ENTMER_ALM FOREIGN KEY (ALM_codigo) REFERENCES ALMOXARIFADO (codigo),
    CONSTRAINT FK_ENTMER_FOR FOREIGN KEY (FOR_codigo) REFERENCES FORNECEDOR_EXT (codigo)
);

-- Tabela SAIDA_MERCADORIA
CREATE TABLE SAIDA_MERCADORIA (
    data DATE NOT NULL,
    ALM_codigo NUMBER NOT NULL,
    MER_codigo NUMBER NOT NULL,
    quantidade NUMBER(4) NOT NULL,
    EMP_matricula NUMBER,
    PRIMARY KEY (MER_codigo, ALM_codigo, data),
    CONSTRAINT FK_SAIMER_ALM FOREIGN KEY (ALM_codigo) REFERENCES ALMOXARIFADO (codigo),
    CONSTRAINT FK_SAIMER_MER FOREIGN KEY (MER_codigo) REFERENCES MERCADORIA (codigo),
    CONSTRAINT FK_SAIMER_EMP FOREIGN KEY (EMP_matricula) REFERENCES EMPREGADO (matricula)
);
