CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    ENDERECO VARCHAR2(200),
    EMAIL VARCHAR2(100)
);

CREATE TABLE PF (
    ID_PF NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER,
    CPF VARCHAR2(14),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE PJ (
    ID_PJ NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER,
    CNPJ VARCHAR2(18),
    RAZAO_SOCIAL VARCHAR2(200),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE PRODUTO (
    ID_PRODUTO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    DESCRICAO VARCHAR2(200),
    PRECO NUMBER(10,2)
);

CREATE TABLE VENDEDOR (
    ID_VENDEDOR NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    EMAIL VARCHAR2(100)
);

CREATE TABLE FONE_CLIENTE (
    ID_FONE_CLIENTE NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER,
    NUMERO VARCHAR2(15),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE FONE_VENDEDOR (
    ID_FONE_VENDEDOR NUMBER PRIMARY KEY,
    ID_VENDEDOR NUMBER,
    NUMERO VARCHAR2(15),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR)
);

CREATE TABLE PRATELEIRA (
    ID_PRATELEIRA NUMBER PRIMARY KEY,
    NOME VARCHAR2(100)
);