CREATE TABLE ITEM_PRODUTO (
    CODIGO_PRO NUMBER NOT NULL,
    NUMERO_PED NUMBER(6) NOT NULL,
    QUANTIDADE NUMBER(5) NOT NULL,
    PRECO_UNITARIO NUMBER(5,2) NOT NULL,
    VALOR_ITEM NUMBER(7,2)
);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT PK_ITEM_PRODUTO
PRIMARY KEY (CODIGO_PRO, NUMERO_PED);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO
FOREIGN KEY (CODIGO_PRO)
REFERENCES PRODUTO(CODIGO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PEDIDO
FOREIGN KEY (NUMERO_PED)
REFERENCES PEDIDO(NUMERO);

COMMENT ON COLUMN ITEM_PRODUTO.CODIGO_PRO IS 'Coluna que informa o Código do Produto.';
COMMENT ON COLUMN ITEM_PRODUTO.NUMERO_PED IS 'Coluna que informa o número do pedido.';
COMMENT ON COLUMN ITEM_PRODUTO.QUANTIDADE IS 'Coluna que informa a quantidade de itens totais.';
COMMENT ON COLUMN ITEM_PRODUTO.PRECO_UNITARIO IS 'Coluna que informa o preço de cada produto do pedido.';
COMMENT ON COLUMN ITEM_PRODUTO.VALOR_ITEM IS 'Coluna que informa o valor dos itens do pedido.';